### ISSUE TITLE
OSM Bright Source: Make source project Mapbox streets compatible

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#25]

**Comment by klokan** [comment]
It seems we target compatibility with MapBox Streets V5 with max zoom level 14 - see comments in #11 

Specification is at:
https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v5/

To ensure compatibility best would be to write tests which downloads some sample tiles from MapBox Streets V5 (or store them in our Github), and compare output of [tileinfo](https://github.com/mapbox/mapnik-vector-tile/tree/master/examples/c%2B%2B) command (or similar) between the two implementations... to ensure these are the same whenever possible.

It would be great if @manuelroth could work on this, while @lukasmartinelli continue to tweak parallelisation and the rendering infrastructure.

**Comment by lukasmartinelli** [comment]
What do you @manuelroth @klokan  think about supporting the newest iteration directly?

https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/#Overview

At the time we hit the `STABLE` release Mapbox Streets v6 will probably have replaced Mapbox Streets v5 (as it happened with v5 and v4).

## Changelog v6

The Changelog section in https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/#Overview

> Most elements will appear 1 or 2 zoom levels lower compared to v5. For example, the street class of road was available from zoom level 12 and up in v5, and is now available from zoom level 11 and up. Depending on how your styles have been put together adjustments may be required when moving projects from v5 to v6.

This is the most important change.

> The maximum vector tile zoom level has increased from z14 to z15. As always, overzooming to even higher zoom levels for rendering is possible.

We probably cannot handle z15 so we need to skip support for that feature.

Additionally there are some new fields in some layers.

**Comment by klokan** [comment]
The decision if v5 or v6 compatibility was for me mostly about being able to render and store 4^15 more tiles (each level has 4x more then previous - so instead of 325 million it is over 1.5 billion tiles -with theoretically only 30% land, but still). It means for sure an MBTiles with hunderds+ GByte size. This starts to be even a problem to host on an ordinary linux VPS.
This does not sound realistic for this project. I am sure we should target max zoom 14.

V6 was redesigned primarily for MapBox GL JS - and new MapBox Studio (not open-source anymore? and not available right now) - it is the future, even MapBox is not yet there...
V5 is used in all existing Mapnik styles in MapBox Studio Classic now - probably to be deprecated soon - but this is what is used now for the server side rendering with mapnik.

By reading the changelog - they seems to mention `localrank` as important feature on more condensed tiles. I wonder if we are able to prepare it in SQL queries?

Perfect V6 compatibility would be amazing result - but we are probably not able to finish it (with z15 tiles).
If we go for V6 which stops at z14 - the visual MapBox styles for v6 would still need to be modified, right?

*I would primarily target 100% v5 compatibility.*

We may introduce some back-compatible GL JS improvements (like elevating some of the features to smaller zoom levels) if required.

**Comment by lukasmartinelli** [comment]
Great insights, did not know about these details! That's what I hoped for in this discussion.

Yes all existing styles in Mapbox Studio Classic are for v5 and if v6 is primarily for MapboxGL they probably will not upgrade the styles of the "old" Mapbox Studio soon.

We have no chance at doing `z15` as `z14` is already quite a challenge.

> I would primarily target 100% v5 compatibility.
> 
> We may introduce some back-compatible GL JS improvements (like elevating some of the features to smaller zoom levels) if required.

Reading through it again it makes alot of sense to **support v5** instead of v6. I guess we are able to **make v5 look good enough** for GL JS.

> If we go for V6 which stops at z14 - the visual MapBox styles for v6 would still need to be modified, right?

Users just won't see all the details they would when overzooming. Styles targeting missing layers don't show up - but we are not really v6 compliant then.

**Comment by lukasmartinelli** [comment]
Good ideas for a name? 
My suggestion is something like `open-streets` (à la `mapbox-streets-v5`).
`osm-bright-2` is a bit too specific when we try to be Mapbox compatible.

**Comment by klokan** [comment]
I was just thinking about the same renaming of osm-bright-2.tm2source in the repo...
`open-streets-v5` sounds good and allow us to work later on v6, if required.
The v5 is MapBox specific, but it will make it easy for people to recognise what from the existing styles they should use...

**Comment by sfkeller** [comment]
Open Streets and open-streets (but not "Openstreets") sounds good to me.

**Comment by klokan** [comment]
TileJSON:
http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v5.json?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ

Preview:
http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v5/page.html?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ#0/0/0

vs our sample:
http://tileserver.maptiler.com/zurich.json

**Comment by manuelroth** [comment]
I will take this approach for comparing two vector tiles. The vector-tile.js library provides ways to select all layers or count how many features are available in this layer. It is a bit easier than comparing the output of tile-info.
![inspect-vector-tiles](https://cloud.githubusercontent.com/assets/1810384/10612673/19db6496-7752-11e5-8713-a60fcb6e5275.png)
![bildschirmfoto 2015-10-20 um 17 45 58](https://cloud.githubusercontent.com/assets/1810384/10612745/77837cb4-7752-11e5-9b5e-2de6ca1825e3.png)

**Comment by klokan** [comment]
For developing the open-streets.tm2source style you will need to get the vector tile of choice after every edit you make... In such case it is easiest to open MapBox Studio Classic, open the source style, then pick the URL of a tile:
![screen shot 2015-10-20 at 19 06 44](https://cloud.githubusercontent.com/assets/59284/10615161/7b4cf74c-775e-11e5-9e9f-56458497a3a3.png)


For example:
http://localhost:3000/source/6/33/22.png?id=tmsource:///Users/klokan/Documents/MapBox/project/countries.tm2source&ifzmgklw

and replace format of the request to:
http://localhost:3000/source/6/33/22.vector.pbf?id=tmsource:///Users/klokan/Documents/MapBox/project/countries.tm2source&ifzmgklw

This way you can iteratively improve the tm2style without generating the MBTiles by our export worker.

What you described above is true for the CI tests (Travis).

**Comment by klokan** [comment]
For a picked tile you need to be able to compare included:
- list of layers and their names (`landuse`)
- in each layer the available features, their attributes and values of attributes (`name_en="Zurich"`)

Comparing can be done either by a custom written JavaScript code as you propose, or by making a dump with defined formatting and using "diff". In both cases - we need to be able to print out on command line the differences - so these can be checked by Travis at later point.

It is important to get an output which helps you to add the missing layers into the .tm2source.
No output means you are done for this tile and you can continue a different one (on a different zoom level for example).

**Comment by manuelroth** [comment]
The first results of my analysis show that we got generally more features in our vector tile than the mapbox-streets tiles. 

I made a script which outputs each layer(landuse) with feature count, classes(agriculture) and types(farm) per class. Then I made a diff on the results of both vector tiles. I put the results into our Google Drive folder, if somebody is interested.

@klokan Would you recommend to remove features which are not present in the streets vector tiles?
The advantage would be, that we get smaller vector tiles. But a style like OSM Carto wouldn't be possible anymore, because not all of the features which OSM Carto needs are present.

**Comment by klokan** [comment]
Could you please make the output more clear, it is a mess now, use hierarchy with spaces/tabs, line oriented output:
```
[layer]
    [class]
        [type]
```
Before printing out order the names in given block alphabetically so that it is really comparable semantically. Complete example could look like:
```
name: open-streets
tile: 10/4141/5356
features: 5000
layers: 10
classes: 20
types: 1000

landuse
    agriculture
        allotments
        farm
    ... /structure alphabetically ordered
```
Don't put this into drive. It is for big binary files primarily.
Gist or a separate github repo (for example) makes better storage for online preview - with online diffs automatically - on the revisions of files.
Save mapbox-streets and rewrite it with open-streets.

Sample:
https://gist.github.com/klokan/8b46f63a3b773416098f/revisions?diff=split

Locally, on your computer you can use vimdiff or other editors to see the diff between files directly.

Tips:
- care in first case about structure (names of layers, names of classes, names of types). What is in MapBox should be in Open as well.
- smaller tile is better tile - if we have everything what is necessary
- in case you already now know about features in Carto which would be missing - add them. But Carto is secondary for us, as there is no .tm2 for it now.
- start with upper levels (smaller zoom numbers)
- be as systematic as possible, document what you do and why (clear commits, forks, etc).

Please make diffs also with mapbox-streets-v6 to get overview of the changes (diff with v5 and existing open).

**Comment by klokan** [comment]
BTW If there is many more information - why at http://tileserver.maptiler.com/zurich/bright-v8.html there are no streets names and no POIs when zoomed-in?

I would start with adding missing things. Tweaking the zoom levels on which things appear.
Deleting and cleaning can be done in the next step...

**Comment by manuelroth** [comment]
@klokan Thanks for the feedback, i tried to implement all of your suggestions. On my gist page(https://gist.github.com/manuelroth) you can find a comparison of the mapbox-streets-v5 style with our open-streets style of one tile on level 0-14. I also generated this output for the mapbox-streets-v6 style. It gets a bit messy if I put all into my gist page. I will probably create a separate repository, with comparison of mapbox-streets-v5 -> mapbox-streets-v6 and mapbox-streets-v5 -> our open-streets.

**Comment by klokan** [comment]
@manuelroth cool thanks.

BTW A gist can have multiple files (sample tiles for all different zoomlevels), instead of one gist for one tile! But anyway...

best would be to create a repo and have a branch for mapbox-streets-v5 with all tiles, another branch for mapbox-streets-v6 and another for open-streets-2015-10-23. Later versions, as we improve the styles, may have separate branches. In GitHub you can easily compare any two branches of choice...

I miss list of attributes of features ("name_en", ...).

**Comment by manuelroth** [comment]
@klokan I created a separate repository(https://github.com/geometalab/comparevectortiles) with branches as you suggested above. I'm not sure yet how to display the list of attributes of features. Would you suggest to output every feature with all of its attributes?- I worry that the output gets huge, because some layers have more than 6000 features.

**Comment by klokan** [comment]
Superb @manuelroth !

- v5 vs v6: 
https://github.com/geometalab/comparevectortiles/compare/mapbox-streets-v5...mapbox-streets-v6

- open vs v5:
https://github.com/geometalab/comparevectortiles/compare/mapbox-streets-v5...open-streets-2015-10-24

- open vs v6:
https://github.com/geometalab/comparevectortiles/compare/mapbox-streets-v6...open-streets-2015-10-24

**Comment by klokan** [comment]
Vector tiles - difference between mapbox-streets-v5 vs mapbox-streets-v6: 
http://osm.tileserver.com/open-streets/bright-v8v5.html
http://osm.tileserver.com/open-streets/bright-v8v6.html

**Comment by klokan** [comment]
Attributes can be added into diffs per layer probably, right?

BTW in CartoCSS typically the layers names are mentioned with prefix # such as `#landuse` and attributes are in brackets so `[name]` - maybe we can have the same notation used in the tile log output and diffs? Some of the attributes are in all layers (such as `[name]`, or `[osm-id]`) but some are specific to a layer - in such case we can write these after layer names - with indentation equal to a class?

**Comment by klokan** [comment]
@manuelroth - we agreed yesterday, that by the end of this week you will have:
- [ ] updated exports of diffs with different alphabetically sorted `[attributes]` under `#layers`.
- [ ] tm2source for zoom level 14 (at this zoomlevel only the layers required for OSM Bright 2 in latest MapBox Studio Classic). It means tiles on z14 - z19 will look the same with open-streets as with mapbox-streets source.
- [ ] from the sample area (possibly Zurich from http://download.bbbike.org/osm/bbbike/Zuerich/, if it has the lake?) you save on your computer with MapBox Studio a vector MBTiles file so that we can test the zooming against Mapnik and MapBox GL JS on weekend.  

First step of work on z14 implementation is probably to identify layers we need there (used in OSM Bright MapBox Studio CartoCSS) - please write a list of the layers first (here or in a new ticket for "z14" on https://github.com/geometalab/open-streets.tm2source) - and track progress on which you have implemented and which are still missing. OK?

It is surprising on the diffs that Mapbox Streets V6 has on z14+z15 together smaller amount of features then V5 on z14 alone. Smaller amount of features in open-streets is a good thing, if we have all geodata required for OSM Bright 2 style (at least now).

**Comment by klokan** [comment]
BTW The complete layer names, with attributes are also printed out in TileJson under "vector_layers" field:
http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v5.json?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ
http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6.json?access_token=pk.eyJ1Ijoib3NtMnZlY3RvcnRpbGVzIiwiYSI6ImNpZnlkb2d0dTAyaDd1M2x6ZGg5cGp4aXQifQ.74RX5npQKmCE1jxsbXYNzQ

**Comment by klokan** [comment]
BTW The vector tiles of Switzerland z8-z14 with our latest styles has ~350 MB - thanks @lukasmartinelli:
http://osm.tileserver.com/open-streets/bright-v8ch.html
http://osm.tileserver.com/switzerland-z14.json

**Comment by lukasmartinelli** [comment]
Oh attention, Switzerland only appears after z8. So one needs to zoom to at least z8. I always fall for that.

**Comment by manuelroth** [comment]
I created an [issue](https://github.com/geometalab/open-streets.tm2source/issues/3) in the open-streets repository to track which layers are still missing.
The extract of bbbike does not have the lake, because the end of the lake is cut off.

**Comment by lukasmartinelli** [comment]
> which layers are still missing.

Great, now we already know more :+1: 

> I created an issue in the open-streets repository to track which layers are still missing.

Can we manage all issues in one repo? It is just easier to keep track off.

**Comment by manuelroth** [comment]
> Can we manage all issues in one repo? It is just easier to keep track off.
The issues to improve the layers are not related to the content of the osm2vectortiles repository. I would like to have them in the open-streets.tm2source repo, because they are related to the style project.

**Comment by lukasmartinelli** [comment]
Ok :+1:

**Comment by lukasmartinelli** [comment]
We discussed once that adding the missing data is more important than removing the data that is too much. But if it is possible we should save as much bandwidth as possible - every MB that is too much directly affects performance. Just rendering two z4 tiles is currently causing 10TB of throughput from SQL server to the export process.

Don't want to be a nitpicker but regarding the source issues discussed above but now we already have several issues discussing stuff that is relevant for both repos in the source repository. (e.g. scale rank discussion).

**Comment by klokan** [comment]
Top priority is having **minimal tiles with OSM Bright 2** compatibility, not perfect compatibility with V5 or V6. Removing stuff is indeed important - every byte in a tile counts - because it is multiplied by 300 millions tiles ;-).

When last time speaking to @manuelroth - I mentioned:
> It is surprising on the diffs that Mapbox Streets V6 has on z14+z15 together smaller amount of features then V5 on z14 alone. Smaller amount of features in open-streets is a good thing, if we have all geodata required for OSM Bright 2 style (at least now).

and
> - smaller tile is better tile - if we have everything what is necessary

**Comment by klokan** [comment]
While doing early testing we have realized some of the vector tiles on z5-z6 has now over 20MBytes (one tile!) in open-streets.tm2source. Cleaning is absolutely essential, such a tile kills Chrome browser when parsed in JavaScript! [comment moved here]

**Comment by klokan** [comment]
What is the status of z14?
During the weekend I expected a sample from @manuelroth - when is it going to be delivered?
I would like to replace online zurich or switzerland tilesets with the latest version we have...

**Comment by lukasmartinelli** [comment]
> During the weekend I expected a sample from @manuelroth - when is it going to be delivered?

We pushed that deadline a week further. Just too many things were missing.
We will deliver the MBTiles for Switzerland this weekend.

**Comment by manuelroth** [comment]
@klokan You can find a new mbtiles of switzerland in the drive folder. It should now be very close to mapbox streets v5. @lukasmartinelli will generate a mbtiles for europe over the weekend, so that we can also see how it looks on the upper layers.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli will generate a mbtiles for europe over the weekend

I will use the HSR infrastructure like last time.

**Comment by klokan** [comment]
Great! Thanks @manuelroth. Updated: http://osm.tileserver.com/open-streets/bright-v8ch.html

@lukasmartinelli feel free to use already the new infrastructure for the test rendering (Amazon for queues  + Google for the virtual machines).

**Comment by sfkeller** [comment]
Excellent work! I have small enhancement proposoal: It seems to me that at z14 the borders are way too much generalized. At z15 (and z13,12,11...) its looks good for me. I did not compare with Mapbox stylebut with OSM Swiss Style e.g. at http://www.nebelkarte.ch/#14/47.2237/8.8314 . See comparison image below.

BTW @klokan : I had to guess the zoom level from the webpage http://osm.tileserver.com/open-streets/bright-v8ch.html you gave. Is it possible to show URL parameters like at Nebelkarte.ch and OSM.org?

**Comment by sfkeller** [comment]
![untitled](https://cloud.githubusercontent.com/assets/43340/11007094/d83db1dc-84c7-11e5-98c5-6fb864c42524.png)

**Comment by lukasmartinelli** [comment]
> It seems to me that at z14 the borders are way too much generalized.

Thanks for the remark. Thats a small change, we just have to show the real water bodies instead of the generalized ones at higher zoom levels.


The map looks much better with the older v5 Mapnik OSM Bright style.
Map looks ok with Mapbox GL but it expects the data one zoom level lower because it was programmed with v6 in mind. Perhaps we can add small improvements that make it a bit better on Mapbox GL.
We now have a blend between v5 and v6 but data in general is at the zoom levels v5 expects it to be.

**Comment by manuelroth** [comment]
@sfkeller Thanks for your comment. For the water_polygons table we have two generalized tables the problem was, that we showed the data off the more generalized table(gen0) on the lower zoomlevel instead of the less generalized table(gen1). (have a look at my commit d8d5e62). @klokan I will add an updated mbtiles file to the drive folder.

**Comment by manuelroth** [comment]
![bildschirmfoto 2015-11-06 um 21 56 41](https://cloud.githubusercontent.com/assets/1810384/11008514/57219802-84d1-11e5-934c-57d50b5206f6.png)
I agree with @lukasmartinelli we probably could add some small improvements specially for Mapbox GL.

**Comment by klokan** [comment]
Our latest Open Streets MBTiles:
http://osm.tileserver.com/open-streets/bright-v8ch.html#13.41/47.2195/8.8220/-11.3
could be compared to MapBox GL JS Bright with:
MapBox Streets V5:
http://osm.tileserver.com/open-streets/bright-v8v5.html#13.41/47.2195/8.8220/-11.3
MapBox Streets V6: 
http://osm.tileserver.com/open-streets/bright-v8v6.html#13.41/47.2195/8.8220/-11.3

**Comment by lukasmartinelli** [comment]
> Top priority is having minimal tiles for OSM Bright 2 style, not a perfect compatibility with V5 or V6. Removing stuff is indeed important - every byte in a tile counts - because it is multiplied by 300 millions tiles ;-).

We have much less data throughput now. From what I see we have 5x to 8x less traffic between Mapnik and PostgreSQL than before. It is still in the TB's though.

**Comment by manuelroth** [comment]
Discussion about v5 and v6 moved #71

**Comment by klokan** [comment]
Natural Earth data integration for ranks is in #46
