### ISSUE TITLE
Tileserver: Possibility to merge multiple mbtiles layers

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#26]
- Usecase: You have a base layer, like mbtiles of swiss osm data. Now you want to put one or multiple other layers on top of this.

**Comment by lukasmartinelli** [comment]
Tried some things with tilelive modules and python landez. There is no existing way of merging mbtiles with different layers together - we would have to write that ourselves.

I propose the following approach:
I someone wants to put a custom data overlay over a custom styled OSM base map he should do that on
the client side with e.g. LeafletJS.

**Comment by sfkeller** [comment]
Putting a "thematic" layer on top of a "base map" is best practice in cartography/GIS.
Since this project is about making map styling so easy (possibly worldwide), we probably have to decide about which users we want to address: Is it both, or the few but important base map stylers or is it the mass users doing thematic maps? If we have to choose, I would concentrate on "base map" stylers.

**Comment by lukasmartinelli** [comment]
> I propose the following approach:
> I someone wants to put a custom data overlay over a custom styled OSM base map he should do that on
> the client side with e.g. LeafletJS.

What I mean is that the user pulls in base map layers but he can still use his custom produced thematic vector layer as an overlay. But he has to specify that in e.g. LeafletJS and the base map and thematic layer are not merged automagically into the same vector tile source.

```javascript
var grayscale = L.tileLayer(mapboxUrl, {id: 'MapID', attribution: mapboxAttribution}),
    streets   = L.tileLayer(mapboxUrl, {id: 'MapID', attribution: mapboxAttribution});

var map = L.map('map', {
    center: [39.73, -104.99],
    zoom: 10,
    layers: [grayscale, cities]
});
```

**Comment by lukasmartinelli** [comment]
> Putting a "thematic" layer on top of a "base map" is best practice in cartography/GIS.
> Since this project is about making map styling so easy (possibly worldwide), we probably have to decide about which users we want to address: Is it both, or the few but important base map stylers or is it the mass users doing thematic maps? If we have to choose, I would concentrate on "base map" stylers.

One nice example where I think osm2vectortiles could have helped alot is this custom Nightlife map of Lisa Stolz (as a bachelor thesis).

http://blog.geofabrik.de/?p=332

Instead of using Geofabrik servers http://sanday.geofabrik.de/night.html?layers=0B
perhaps she could have used our vector tiles to do the same styling.

![tileserver_test_page](https://cloud.githubusercontent.com/assets/1288339/10436591/9bac3508-7127-11e5-944b-02ca142514ca.jpg)

**Comment by lukasmartinelli** [comment]
In the bachelor thesis I found this sentence:

> Wie auch Kosmtik greift die Software auf PostGIS zu und ist mit der neuen Version
TileMill 2 noch immer ein gängiges Programm. TileMill 2 benutzt zudem Vektortiles,
die auf dem Server des Herstellers MapBox liegen. TileMill 2 ist im Vergleich zu
TileMill 1 stärker an den Hersteller gebunden. Da man bei der Erstellung des neuen
Kartenstils möglichst unabhängig bleiben möchte wird von der Nutzung von TileMill
abgesehen und stattdessen Kosmtik verwendet.

And this is really what we are trying to solve here, by providing our own vector tiles people can use Mapbox Studio Classic. Great to see that the problem really exist.

**Comment by klokan** [comment]
The MapBox Streets example shows that two layer names can be combined with comma:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6/10/299/386.vector.pbf?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q

TileJSON is concatenated as well:
https://b.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6.json?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q

This can be trivially implemented in TileServer-PHP, because vector tiles are designed in a way which supports merging by direct binary concatenation...
