### ISSUE TITLE
Evaluate wikimaps tm2source

### ISSUE THREAD

**Issue by klokan** [geometalab/osm2vectortiles#28]
The [wiki maps](https://maps.wikimedia.org/) mentioned also in #13 seems to be powered by OSMBright:
https://github.com/kartotherian/osm-bright.tm2
https://github.com/kartotherian/osm-bright.tm2source

This may be worth trying - including their software stack - to compare with other alternatives.
Adjustments required - especially to prepare vtiles into MBTiles efficiently, and if possible stop at upper zoom-levels like 14 and overzoom on drawing only.

**Comment by lukasmartinelli** [comment]
The quality of the tm2source is very good. I am tempted to switch to osm2pgsql just for this reason because it will save us alot of work but then there are all the disadvantages from an engineering perspective.

I want to go the route of imposm3. And because we need to refactor alot of the queries anyway I would try to be directly compliant with mapbox-streets-v6 instead of mapbox-streets-v5.
Since the bottleneck is the rendering of the world it is very important that we can deliver the fastest possible performance there and imposm gives us alot of room to optimize already at the import step.
However we can learn alot of the tm2source of wikimedia. Especially at which zoom level they show what.

## Wikimedia tm2source with osm2pgsql

Advantages:
- **Mapbox compliant styles for free (big one!)**
- Reuse (don't maintain a separate style)

Disadvantages:
- Slower tile generation (min. 2x) <- this could be improved by additional tuning
- Performance tuning required for alot of queries (stored procs)
- Slower import (6x)
- Requires tweaking to work with latest Mapbox vt-util functions
- GPL license

## Slower PostgreSQL

Another fun fact: It probably makes sense to create stored procedures just to save the bytes when transmitting the queries because the queries get sent billion of times over the wire (or IPC). In the docker daemon I see dozens of GBs that were sent from the export container to the database container.
In the case of wikimedia it actually sent 30GB of queries just for rendering switzerland (and  not even down to z14).

Attributes are are stored in individual columns which are not indexed by default. And if we index them
we have the space tradeoff. With imposm we can map buildings directly into their own table and
only leave the tags we actually need.

One of the smallest queries is the query for buildings:

```sql
SELECT osm_id, way
FROM planet_osm_polygon
WHERE
z(!scale_denominator!) >= 14
AND building IS NOT NULL
AND building <> 'no'
AND way && !bbox!
```

This query is not as bad because the GIST index already restricts the data to the polygons that are in the tile, but then all polygons need to be scanned whether they are buildings or not. And this pattern occurs
all over the queries.

And here the query for the roads. The mapping of the appropriate OSM tags happens in the queries, while in imposm it happens in the import directly. The `CASE` statement is not very performance critical though. But the `WHERE` clause hits the `railway` and `highway` attributes quite often which require an additional index to get the performance.

```sql
SELECT osm_id, way, class, "is" FROM (
SELECT
    osm_id,
    way,
    CASE
      WHEN highway IN ('motorway', 'motorway_link', 'driveway') THEN highway
      WHEN highway IN ('primary', 'primary_link', 'trunk', 'trunk_link', 'secondary', 'secondary_link', 'tertiary', 'tertiary_link') THEN 'main'
      WHEN highway IN ('residential', 'unclassified', 'living_street') THEN 'street'
      WHEN highway IN ('pedestrian', 'construction') OR access = 'private' THEN 'street_limited'
      WHEN railway IN ('rail', 'monorail', 'narrow_gauge', 'subway', 'tram') THEN 'major_rail'
      WHEN highway IN ('service', 'track') THEN 'service'
      WHEN highway IN ('path', 'cycleway', 'ski', 'steps', 'bridleway', 'footway') THEN 'path'
      WHEN railway IN ('funicular', 'light_rail', 'preserved') THEN 'minor_rail'
      ELSE bail_out('Unexpected road row with osm_id=%s', osm_id::TEXT)
    END AS class,
    z_order,
    CASE
      WHEN bridge IS NOT NULL AND bridge <> 'no' AND bridge <> '0' THEN 'bridge'
      WHEN tunnel IS NOT NULL AND tunnel <> 'no' AND tunnel <> '0' THEN 'tunnel'
      ELSE 'road'
    END AS "is"
  FROM planet_osm_line
  WHERE
    (
        (
          highway IN ('motorway', -- 'motorway'
            'primary', 'primary_link', 'trunk', 'trunk_link' -- 'main'
          )
          AND z(!scale_denominator!) >= 6
        )
        OR
        ( -- 'main'
          highway IN ('secondary', 'secondary_link')
          AND z(!scale_denominator!) >= 9
        )
        OR
        ( -- 'main'
          highway IN ('tertiary', 'tertiary_link')
          AND z(!scale_denominator!) >= 12
        )
        OR
        ( -- 'street'
          highway IN ('residential', 'unclassified', 'living_street')
          AND z(!scale_denominator!) >= 12
        )
        OR
        ( -- 'street_limited'
          (highway IN ('pedestrian', 'construction') OR access = 'private')
          AND z(!scale_denominator!) >= 12
        )
        OR
        ( -- 'major_rail'
          railway IN ('rail', 'monorail', 'narrow_gauge', 'subway', 'tram')
          AND z(!scale_denominator!) >= 12
        )
        OR
        ( -- 'motorway_link'
          highway IN ('motorway_link')
          AND z(!scale_denominator!) >= 13
        )
        OR
        ( -- 'service'
          highway IN ('service', 'track')
          AND z(!scale_denominator!) >= 14
        )
        OR
        ( -- 'driveway'
          highway IN ('driveway')
          AND z(!scale_denominator!) >= 14
        )
        OR
        ( -- 'path'
          highway IN ('path', 'cycleway', 'ski', 'steps', 'bridleway', 'footway')
          AND z(!scale_denominator!) >= 14
        )
        OR
        ( -- 'minor_rail'
          railway IN ('funicular', 'light_rail', 'preserved')
          AND z(!scale_denominator!) >= 14
        )
      )
    AND way && !bbox!
) data JOIN (
  VALUES
    ('motorway', 1000),
    ('main', 900),
    ('street', 800),
    ('motorway_link', 700),
    ('street_limited', 600),
    ('driveway', 500),
    ('major_rail', 400),
    ('service', 300),
    ('minor_rail', 200),
    ('path', 100)
) AS ordertable(feature, prio) ON class=feature
  ORDER BY z_order + prio +
    CASE "is"
      WHEN 'tunnel' THEN -100000
      WHEN 'road' THEN 0
      WHEN 'bridge' THEN 100000
      ELSE bail_out('Unexpected row with is=%s, osm_id=%s', "is", osm_id::TEXT)::INT
    END
)
```

**Comment by klokan** [comment]
I like the imposm3 more and more as well. OmniScale guys do a good job on the tool it seems. It is a database designed for fast access and rendering.
My +1 on choosing it.

It means we go with our own forked tm2source (which was expected in the beginning of the project).
The efficient and complete definition of the data style seems to be the most critical point of the whole project. Inspiration from Wikimedia layers is welcome.

Good point about the stored queries, but it means there will be extra SQL dump with saved queries which we need to distributed together with our tm2source and executed on PostgreSQL before we let Mapnik/Tilelive to read the datastyle.

**Comment by lukasmartinelli** [comment]
Discussion for our custom tm2source by @manuelroth  should be moved to a new issue. Evaluation of the tm2source has been completed.

**Comment by lukasmartinelli** [comment]
We can take a look at the original osm bright tilemill project for the queries.

https://github.com/mapbox/osm-bright/blob/master/osm-bright/osm-bright.imposm.mml
