### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by lukasmartinelli** [geometalab/osm2vectortiles#47]
I suggest we move all code into a `src` directory and then have a flat structure with our components (not like the latest change where we have everything categorized into `import` and `export`) for all
components. We can also create a `docs` directory with the detailed documentation.
I took a look around and many projects use an approach like that.

```
├── docs
├── import
├── export
└── src
    ├── gatling
    ├── import (the old `imposm3` container)
    ├── open-streets.tm2source
    ├── postgis
    ├── tileserver
    ├── compare-vector-tiles
    ├── export (the old tilelive/worker container)
    ├── verifier
    ├── scheduler
    ├── aggregator
    ├── tileserver
    └── water
```
This allows to have the import and export folders at the root project (which now is not possible) and just operate the entire stack with docker-compose from there.

Water SHP files and PBFs are put into the `import` directory, `import` container and `water` container are run and if people want to create their custom vector data extract of a country they run the `export` container and can find the files in the `export` dir.

The tileserver will probably only be used from Docker Hub directly (via CLI or Kitematic) but if people
want to do a import/export with our solution they should use docker-compose (as it makes managing all the state much easier).

**Comment by klokan** [comment]
+1. This is fine.

We may move the open-streets.tm2source into https://github.com/geometalab/open-streets.tm2source

**Comment by lukasmartinelli** [comment]
> We may move the open-streets.tm2source into https://github.com/geometalab/open-streets.tm2source

I'm not sure whats better..

Points for it:
- Easier for people to explore
- tm2source projects are usually in their own repo (Kartotherian and the others do the same)
- Since comparison already happens there it makes sense to move it there as well

Points against it:
- open-streets.tm2source is tightly coupled with water import and imposm schema (imposm3)
- issue and documentation management is easier with one monorepo
- we perhaps have to include it in this repo as git submodule or better git subtree - but both are a pain to work with

**Comment by klokan** [comment]
Regarding the split to two repos decide together with @manuelroth. I don't care that much... the pros/cons are mentioned.

If it is in single repo - the tm2source should be in the root probably - as all other things in /src/ are Docker containers. The open-streets.tm2source is quite different the everything else in /src.

Should the travis tests run on style update or it should run on Dockerfiles updates? Now it is on both...

While you work on your thesis, there should be a single place for issues and milestones.

If we go for single repo, we should probably git push the diff branches such as `mapbox-streets-v5` or `mapbox-streets-v6` into this repo (maybe as 'diff/mapbox-streets-v5'?) and remove the other repo completely? It makes no sense to have a repo only for diffs... It is helpful to have online preview like:
geometalab/comparevectortiles@mapbox-streets-v5...mapbox-streets-v6
(but this could be also generated into HTML and saved into gh-pages, with something like http://technogems.blogspot.ch/2011/09/generate-side-by-side-diffs-in-html.html - the question is how much time to spend with this, we need some clear visualisation, and github diffs are almost perfect and done now).

None of these things are extremely important for the final result of the project.
It should be just easy to use for people, documented and it should make sense in usage.
I like if people can use tileserver easily from Kitematic. The import/export deps managed by docker compose are perfect.

Some ideas (refuse or accept as you wish):
- Shall we unify the names of dockers to verb-based? "verify" instead of "verifier", or "serve" instead of "tileserver", "import", "export", etc.?
- This would give `water` -> `import-water`?
- Or `gatling` maybe `test-performance`?
- Not sure about `scheduler` (despite the fact I suggested it) - it is not really scheduling...

**Comment by lukasmartinelli** [comment]
Let's move it into a separate repo and document all differences between our vector tiles and those from Mapbox there. Then we can also setup Travis there to only test generating the vector tiles and log its differences and on the main repo we can verify that the entire stack runs (one huge integration test).

Let's leave it with the diffs like it is today. We can present the diffs in a nice way at the end of the project and they will also find their way into our thesis documentation.

I like the verb based component names (works for everything except `postgis`):
- `postgis`
- `serve`
- `import`
- `export`
- `verify`
- `merge`
- `import-water`
- `enqueue-jobs`
- `test-performance`

Our components grow and grow :) I understand why Kartotherian is such a huge project now.

**Comment by klokan** [comment]
+1

Please proceed.

On the repo osm2vectortiles may be set also docker hub webhook - to update the images of containers (which don't need rebuild in case of change of the style).

**Comment by lukasmartinelli** [comment]
> Let's move it into a separate repo and document all differences between our vector tiles and those from Mapbox there.

**I really want to revert that decision.**

## Why?

The more I work with the two repos the more painful it is. The imposm mapping schema and the open-streets.tm2source project are just too intermingled / dependant on each other.
If I add something in imposm I also need to change something in open streets most of the times.

Then I need two commits which have basically the same commit message. And if I work on a feature branch in imposm I have to create two feature branches.

I also think we want to rely on SQL functions to reduce redundancy and stay DRY 
https://github.com/geometalab/open-streets.tm2source/commit/207c501f74958e7aa37434fd8406c89889f51900 (especially since the classification is done in SQL) which requires a `prepare` container  https://github.com/geometalab/osm2vectortiles/commit/418222fe5a0357850ec0db491e96a44f2e599c71 needing access to the SQL files to update.

Also export container is now cloning the open-streets repo down into the container but that also means that if the open-streets master branch no longer works together with the current master branch it just starts failing.

## If we move back

We already have some discussion on the repository in open-streets but we can leave that archived there for some time or I try to copy it manually back here (as citations).

I can merge the commits from open-streets (including history) back into this repo with git subtree.

**Comment by lukasmartinelli** [comment]
It is your call @manuelroth  :grin:

**Comment by klokan** [comment]
> Regarding the split to two repos decide together with @manuelroth. I don't care that much... the pros/cons are mentioned.

**Comment by manuelroth** [comment]
@lukasmartinelli Yes, you are right. It's really a pain to work with two branches on separate repositories. Let's merge the style project back in.
