### ISSUE TITLE
Mapping Schema

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#52]
Layer landuse:

```
#landuse
- agriculture
    - allotments
    - farm
    - farmland
    - farmyard
    - orchard
    - plant_nursery
    - vineyard
- cemetery
    - cemetery, christian, jewish
- glacier
    - glacier
- grass
    - grass
    - grassland
    - meadow
- hospital
    - hospital
- industrial
    - industrial
- park
    - park, dog_park, common, garden, golf_course, playground, recreation_ground, nature_reserve, sports_centre, zoo, village_green
- pitch
    - athletics, chess, pitch
- sand
    - sand
- school
    - school, college, university
- scrub
    - scrub
- wood
    - wood, forest
```

**Comment by lukasmartinelli** [comment]
Let's use this issue for schema discussions instead of https://github.com/geometalab/open-streets.tm2source/issues/3

Here is a first megaschema of our mapping. Drawing it took quite some time but showed up where data is still missing and where we need to improve the schema. We should probably refine this tomorrow @manuelroth.

This is not how the schema looks today but how it should look (except things like `place_label` where we need to find out more).

On the left you see the imposm tables and on the right how the layers should look like in the end.
This helps identifying where data from imposm is still missing (e.g. names in different languages).

![mapping_schema](https://cloud.githubusercontent.com/assets/1288339/10890322/b660820c-8197-11e5-86dd-8cdb877e3bd4.png)

**Comment by lukasmartinelli** [comment]
Some notes what we should discuss about the layers tomorrow, what the problems are and how progress is.


## Admin
In order to be able to merge the scalerank values from natural earth we should provide an empty field `scalerank` on the imposm table that can then be replaced by the natural earth data.
If there is no `scalerank` value we can calculate it from the area or something.

- [ ] But in general we just need to do a thorough investigation what the state of admin layers is

## Roads
Tunnels, roads and bridges are displayed correctly, sometimes the shield look a bit different.
Later on we might also check how well our generalization works on the roads (do we strip no enough data away?).
Railways are not good yet as too many rails are classified as `major`.

- [ ] Check railway classification
- [ ] Check shield labels

## Aeroways

- [ ] Add mapping
- [ ] Check whether labels are included in the POIs
- [ ] Verify different types of aeroways actually come out correcly



## Water

The water labels and marine labels we need to evaluate. I have never checked whether these are mapped correctly. I think marine labels will come from the water table as well but I am not sure.

- [ ] Find out more about marine label
- [ ] Check labels for fjords and bays
- [ ] Check labels for lakes
- [ ] Where are the labels for Oceans?

## Houses

We got this one, just need to cleanup. I saw that in Mapbox v6 very big buildings are also shown at lower zoom levels (not only z14).

- [ ] Remove unnecessary values from housing and numbers table (like name)
- [ ] How good are the place labels?

## Point of Interests

Correct maki labels and classes need to be handled in the queries but we still need to demistify the
`network` tag and find the correct values. Also Mapbox specifies the `ref` value, but I could not found a POI on the official OSM Bright map with a `ref` value (so it is really necessary?).

We also need to merge transport points and areas into the point of interests. It might also be that aeroway points like helipads or airports should be contained in the POIs as well.

- [ ] Are aeroways points contained within POIs?
- [ ] Add network
- [ ] Add ref
- [ ] Include transport points into the POI table

## Landusages
We already added alot of tags and think are complete there.
I haven't ever checked the `#landuse_overlay` layer though.

- [ ] Verify landusages_overlay
- [ ] Verify landusages

## Barriers

Barriers shouldn't be too much work. We just need to look into it and check whether we have most of the barriers at z14. I think we are close but we just have never checked.

- [ ] Verify barrier data
- [ ] There is a bit a weird thing in the documentation where it is not sure whether barrier_lines only contains lines or additionally polygons or even points as well.

**Comment by lukasmartinelli** [comment]
Code is messy but we can now automatically generate mapping diagrams from the tm2source (where I parse the SQL functions for referenced tables) and mapping.yml.

https://github.com/geometalab/osm2vectortiles/commit/9c7b67f33fd7fd56b725bad4f5d592642c27c380

Looks like this (old version - not our improved mapping, so we see lot of unused tables).

![table_layer_diagram](https://cloud.githubusercontent.com/assets/1288339/10921104/04ae5fd8-8274-11e5-88e2-f44d1c465cef.png)

**Comment by lukasmartinelli** [comment]
Creating the first diagram in the editor actually took more time than writing code to generate the second diagram :grinning:

**Comment by lukasmartinelli** [comment]
When you are improving the queries you can actually look in the newest generated diagram which layers you need to adapt.

**Layers referencing stuff in a circle means that the tables has not been found** so the query must be adapted to our new naming scheme.
And in the end every table should be at least once be used from one layer (otherwise we should remove it).

![table_layer_diagram](https://cloud.githubusercontent.com/assets/1288339/10921328/5252b594-8275-11e5-8873-84b3fd99e1da.png)
