### ISSUE TITLE
Improved Queries Discussion

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#64]
@lukasmartinelli We have right now some generalized tables which are based on a type filters in the imposm mapping. 
```sql
water_lines_gen0:
    source: water_lines
    tolerance: 0.0
    sql_filter: type IN ('river', 'canal')
```
This is not a very good idea, as we do the filtering per type on other layers in the queries not in the imposm mapping. Let's decide that we use, generalized tables only for real generalizations based on the area of the polygon.
Like this:
```sql
 water_polygons_gen1:
    source: water_polygons
    sql_filter: ST_Area(geometry)>50000.000000
    tolerance: 50.0
```

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli We have right now some generalized tables which are based on a type filters in the imposm mapping.

Yes I know. Assumption is that on the lower zoom levels different classes are shown - but I don't know whether it is really like that. We can check that out using the new Debug Viewer whether certain classes are hidden at lower zoom levels.

I agree. Let's only do geometry simplification in the generalized tables. Filtering out the unnecessary types in the query is not really as bad for performance as on higher zoom levels (because rendering to z8 is quite fast anyway) and it is much cleaner that way :+1:

**Comment by lukasmartinelli** [comment]
We reviewed mapping and queries.

![table_layer_diagram](https://cloud.githubusercontent.com/assets/1288339/10965994/dcb03360-83b0-11e5-8a69-c620e74633f0.png)

**Comment by lukasmartinelli** [comment]
We can actually find out whether a state is disputed (it is a bit messy though): https://github.com/kartotherian/osm-bright.tm2source/blob/master/data.yml#L378-L384

**Comment by lukasmartinelli** [comment]
I suggest we skip the `#state_label`. In Mapbox v5 it is only partially completed (and no one of the styles is using it - Kartotherian neither).

It seems to be something for english speaking countries (supporting only US, Canada, Australia and GB) and it is not really clear for which admin_level this should be or whether it is a handcrafted layer.

In Mapbox v6 data set they additionally support chinese provinces but that's it. Some v6 styles start displaying it but they still look good if there is no state_label present.

![mapbox_studio_classic](https://cloud.githubusercontent.com/assets/1288339/10980264/61bbfdc8-8401-11e5-8889-825411751a9d.png)

We can actually remove some data if we skip the layer because the state_label requires the correct area to be displayed and therefore needs the `admin` polygons and not the `places` table like other labels.

**Comment by manuelroth** [comment]
Okey, I agree as it has no clear perpose and we can save some data. I will remove the unused fields of the admin table in the imposm mapping and remove the layer of the source project

**Comment by lukasmartinelli** [comment]
> Okey, I agree as it has no clear perpose and we can save some data. I will remove the unused fields of the admin table in the imposm mapping and remove the layer of the source project

Let's check it out tomorrow when the world is imported whether we already get something useful out - if not we leave it.

**Comment by lukasmartinelli** [comment]
- Funicular stations are tagged as "railway=station" and therefore have a too high scalerank
- Because we modify the scalerank some stuff without area appears to early
- No distinction between muslim and christian place of worships
- Too many shields (because we always return `default`?)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992771/a9ad476e-8469-11e5-9988-00431e04d8a5.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992782/c5766c50-8469-11e5-9b9e-98f95096f5e6.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992809/fcc46b30-8469-11e5-8bd8-6c2b778a61d0.png)


![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992852/5397b0b6-846a-11e5-9773-3b81980f10b7.png)


OSM Tag for harbor?

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992876/91d70174-846a-11e5-9a4c-198768a3e5a8.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992894/bf1a7ea4-846a-11e5-9b06-44c1cd6884e0.png)

**Comment by lukasmartinelli** [comment]
Golfclubs are missing?

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10992973/83b66e08-846b-11e5-9f99-03ef01016b93.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993001/b05f45c4-846b-11e5-8cb3-0a4a775369fe.png)


![5hkvwvgfks](https://cloud.githubusercontent.com/assets/1288339/10993051/261e69a2-846c-11e5-81a4-ec756ef63e38.gif)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993113/a8e4f09a-846c-11e5-9996-3044e73282bf.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993167/01300460-846d-11e5-97b7-2231b1e2c4fd.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993218/5ab3e308-846d-11e5-94b2-e6edb1b2b538.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993263/bbee1832-846d-11e5-99ed-ab94c5fcf305.png)

![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10993425/f3f45222-846e-11e5-9da7-704384b5c400.png)

**Comment by lukasmartinelli** [comment]
For admin layers:
- If zoom level <= z2 then all admin_level <= 3 are shown
- After z3 more and more admin_level=4 are shown depending on the area of the admin layer
- Until z6 where **all** admin_level=4 polygons are shown

**Comment by lukasmartinelli** [comment]
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1288339/10994179/e3e04e94-8474-11e5-938b-15622ce9717a.png)
