### ISSUE TITLE
If required OSM Bright Visual Styles adjustments

### ISSUE THREAD

**Issue by manuelroth** [geometalab/osm2vectortiles#8]
- If required adjust visual styles of OSM Bright -> https://github.com/mapbox/mapbox-studio-osm-bright.tm2

**Comment by lukasmartinelli** [comment]
The only visual style we have to change would be the fonts (because they are custom Mapbox licensed). But this is we serving the tiles, not when the user styles the vectortiles MBTiles in Mapbox Studio.

We could search and replace the custom licensed fonts in our tileserver and replace them with their OSS alternatives (like we do it already with the `source` url).

**Comment by sfkeller** [comment]
Regarding Open Source Fonts: OSM main map took "DejaVu Sans" (http://dejavu-fonts.org ) because it's one of the few fonts which support non-european languages (like Hebrew). 
Then we could consider also:
* "Google Noto": https://www.google.com/get/noto/
* "Source Han Sans" and/or "Sans Pro" (panasiatic character set) http://blog.typekit.com/2014/07/15/introducing-source-han-sans/ and https://github.com/adobe-fonts/source-han-sans

**Comment by lukasmartinelli** [comment]
> Regarding Open Source Fonts: OSM main map took "DejaVu Sans" (http://dejavu-fonts.org ) because it's one of the few fonts which support non-european languages (like Hebrew).

Yes supporting original place names is very important.
The new Mapbox specification also supports all labels in English, Spanish, French, German, Russian and Chinese.

**Comment by lukasmartinelli** [comment]
Kartotherian uses Google Noto for http://maps.wikimedia.org

https://github.com/kartotherian/osm-bright.fonts

**Comment by klokan** [comment]
The OSM-Bright2 repo uses OpenSans font, which is freely available:
https://github.com/mapbox/mapbox-studio-osm-bright.tm2/blob/master/labels.mss#L21
So there is probably no need for change at all...

But the OSM-Brigth.tm2 on GitHub has been upgraded from mapbox-streets-v5 to mapbbox-streets-v6, with the upgrade from release v1.0 to v2.0. It seems the changes in the style are not huge: https://github.com/mapbox/mapbox-studio-osm-bright.tm2/commits/master
